LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so
LoadModule proxy_balancer_module modules/mod_proxy_balancer.so
LoadModule slotmem_shm_module modules/mod_slotmem_shm.so
LoadModule lbmethod_byrequests_module modules/mod_lbmethod_byrequests.so

<VirtualHost *:80>
    ServerName localhost
    <Proxy balancer://novacluster>
        BalancerMember http://tom1cont:8080
        BalancerMember http://tom2cont:8080
        BalancerMember http://tom3cont:8080
        ProxySet lbmethod=byrequests
    </Proxy>
    ProxyPass / balancer://novacluster/
    ProxyPassReverse / balancer://novacluster/
</VirtualHost>
